# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gomschema

# /// Allegiance is an enumeration of allegiance types reduced to a single field.
class Allegiance(object):
    None_ = 0
    Alliance = 1
    Empire = 2
    Federation = 3
    Independent = 4
    PilotsFederation = 5

