# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gomschema

import flatbuffers

# /// Galactic coordinate for a system.
class Coordinate(object):
    __slots__ = ['_tab']

    # Coordinate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Coordinate
    def X(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Coordinate
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Coordinate
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateCoordinate(builder, x, y, z):
    builder.Prep(8, 24)
    builder.PrependFloat64(z)
    builder.PrependFloat64(y)
    builder.PrependFloat64(x)
    return builder.Offset()
