// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var gomschema = gomschema || {};

/**
 * Government is an enumeration of government types reduced to a single field.
 *
 * @enum {number}
 */
gomschema.Government = {
  None: 0,
  Anarchy: 1,
  Communism: 2,
  Confederacy: 3,
  ooperative: 4,
  Corporate: 5,
  emocracy: 6,
  Dictatorship: 7,
  Feudal: 8,
  Patronage: 9,
  Prison: 10,
  PrisonColony: 11,
  Theocracy: 12
};

/**
 * Government is an enumeration of government types reduced to a single field.
 *
 * @enum {string}
 */
gomschema.GovernmentName = {
  0: 'None',
  1: 'Anarchy',
  2: 'Communism',
  3: 'Confederacy',
  4: 'ooperative',
  5: 'Corporate',
  6: 'emocracy',
  7: 'Dictatorship',
  8: 'Feudal',
  9: 'Patronage',
  10: 'Prison',
  11: 'PrisonColony',
  12: 'Theocracy'
};

/**
 * Allegiance is an enumeration of allegiance types reduced to a single field.
 *
 * @enum {number}
 */
gomschema.Allegiance = {
  None: 0,
  Alliance: 1,
  Empire: 2,
  Federation: 3,
  Independent: 4,
  PilotsFederation: 5
};

/**
 * Allegiance is an enumeration of allegiance types reduced to a single field.
 *
 * @enum {string}
 */
gomschema.AllegianceName = {
  0: 'None',
  1: 'Alliance',
  2: 'Empire',
  3: 'Federation',
  4: 'Independent',
  5: 'PilotsFederation'
};

/**
 * Security level is system-specific and determines how aggressive law enforcement is.
 *
 * @enum {number}
 */
gomschema.SecurityLevel = {
  None: 0,
  Anarchy: 1,
  Low: 2,
  Medium: 3,
  High: 4
};

/**
 * Security level is system-specific and determines how aggressive law enforcement is.
 *
 * @enum {string}
 */
gomschema.SecurityLevelName = {
  0: 'None',
  1: 'Anarchy',
  2: 'Low',
  3: 'Medium',
  4: 'High'
};

/**
 * @enum {number}
 */
gomschema.FacilityType = {
  None: 0,
  CivilianOutpost: 1,
  CommercialOutpost: 2,
  CoriolisStarport: 3,
  IndustrialOutpost: 4,
  MilitaryOutpost: 5,
  MiningOutpost: 6,
  OcellusStarport: 7,
  OrbisStarport: 8,
  ScientificOutpost: 9,
  PlanetaryOutpost: 10,
  PlanetaryPort: 11,
  PlanetarySettlement: 12,
  Megaship: 13,
  AsteroidBase: 14,
  FleetCarrier: 15
};

/**
 * @enum {string}
 */
gomschema.FacilityTypeName = {
  0: 'None',
  1: 'CivilianOutpost',
  2: 'CommercialOutpost',
  3: 'CoriolisStarport',
  4: 'IndustrialOutpost',
  5: 'MilitaryOutpost',
  6: 'MiningOutpost',
  7: 'OcellusStarport',
  8: 'OrbisStarport',
  9: 'ScientificOutpost',
  10: 'PlanetaryOutpost',
  11: 'PlanetaryPort',
  12: 'PlanetarySettlement',
  13: 'Megaship',
  14: 'AsteroidBase',
  15: 'FleetCarrier'
};

/**
 * @enum {number}
 */
gomschema.LandingPad = {
  None: 0,
  Small: 1,
  Medium: 2,
  Large: 3
};

/**
 * @enum {string}
 */
gomschema.LandingPadName = {
  0: 'None',
  1: 'Small',
  2: 'Medium',
  3: 'Large'
};

/**
 * @enum {number}
 */
gomschema.CommodityType = {
  None: 0,
  Chemicals: 1,
  ConsumerItems: 2,
  LegalDrugs: 3,
  Foods: 4,
  IndustrialMaterials: 5,
  Machinery: 6,
  Medicines: 7,
  Metals: 8,
  Minerals: 9,
  Slavery: 10,
  Technology: 11,
  Textiles: 12,
  Waste: 13,
  Weapons: 14,
  Unknown: 15,
  Salvage: 16
};

/**
 * @enum {string}
 */
gomschema.CommodityTypeName = {
  0: 'None',
  1: 'Chemicals',
  2: 'ConsumerItems',
  3: 'LegalDrugs',
  4: 'Foods',
  5: 'IndustrialMaterials',
  6: 'Machinery',
  7: 'Medicines',
  8: 'Metals',
  9: 'Minerals',
  10: 'Slavery',
  11: 'Technology',
  12: 'Textiles',
  13: 'Waste',
  14: 'Weapons',
  15: 'Unknown',
  16: 'Salvage'
};

/**
 * Commodity is a type of item that can be traded within the game. At the moment,
 * the categories are small enough I decided to just enumerate them right here.
 *
 * @constructor
 */
gomschema.Commodity = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.Commodity}
 */
gomschema.Commodity.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {gomschema.Commodity=} obj
 * @returns {gomschema.Commodity}
 */
gomschema.Commodity.getRootAsCommodity = function(bb, obj) {
  return (obj || new gomschema.Commodity).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * Elite Dangerous' internal ID for the commodity acts as the key.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.Commodity.prototype.commodityId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.Commodity.prototype.mutate_commodity_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * Name can be localized as long as the English name is preserved for hashing.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Commodity.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * What type of item is this.
 *
 * @returns {gomschema.CommodityType}
 */
gomschema.Commodity.prototype.categoryId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {gomschema.CommodityType} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.CommodityType.None;
};

/**
 * @param {gomschema.CommodityType} value
 * @returns {boolean}
 */
gomschema.Commodity.prototype.mutate_category_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Whether the item is known to be rare.
 *
 * @returns {boolean}
 */
gomschema.Commodity.prototype.isRare = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Commodity.prototype.mutate_is_rare = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Whether the item is known to be marketable.
 *
 * @returns {boolean}
 */
gomschema.Commodity.prototype.isNonMarketable = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Commodity.prototype.mutate_is_non_marketable = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * The average galactic market price in credits.
 *
 * @returns {number}
 */
gomschema.Commodity.prototype.averageCr = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Commodity.prototype.mutate_average_cr = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
gomschema.Commodity.startCommodity = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} commodityId
 */
gomschema.Commodity.addCommodityId = function(builder, commodityId) {
  builder.addFieldInt64(0, commodityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
gomschema.Commodity.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.CommodityType} categoryId
 */
gomschema.Commodity.addCategoryId = function(builder, categoryId) {
  builder.addFieldInt8(2, categoryId, gomschema.CommodityType.None);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isRare
 */
gomschema.Commodity.addIsRare = function(builder, isRare) {
  builder.addFieldInt8(3, +isRare, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isNonMarketable
 */
gomschema.Commodity.addIsNonMarketable = function(builder, isNonMarketable) {
  builder.addFieldInt8(4, +isNonMarketable, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} averageCr
 */
gomschema.Commodity.addAverageCr = function(builder, averageCr) {
  builder.addFieldInt32(5, averageCr, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
gomschema.Commodity.endCommodity = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} commodityId
 * @param {flatbuffers.Offset} nameOffset
 * @param {gomschema.CommodityType} categoryId
 * @param {boolean} isRare
 * @param {boolean} isNonMarketable
 * @param {number} averageCr
 * @returns {flatbuffers.Offset}
 */
gomschema.Commodity.createCommodity = function(builder, commodityId, nameOffset, categoryId, isRare, isNonMarketable, averageCr) {
  gomschema.Commodity.startCommodity(builder);
  gomschema.Commodity.addCommodityId(builder, commodityId);
  gomschema.Commodity.addName(builder, nameOffset);
  gomschema.Commodity.addCategoryId(builder, categoryId);
  gomschema.Commodity.addIsRare(builder, isRare);
  gomschema.Commodity.addIsNonMarketable(builder, isNonMarketable);
  gomschema.Commodity.addAverageCr(builder, averageCr);
  return gomschema.Commodity.endCommodity(builder);
}

/**
 * Trade is a discrete entry for a Commodity that is or can be traded at with
 * a number of units and a value.
 *
 * @constructor
 */
gomschema.Trade = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.Trade}
 */
gomschema.Trade.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * Which commodity this descrbes.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.Trade.prototype.commodityId = function() {
  return this.bb.readUint64(this.bb_pos);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.Trade.prototype.mutate_commodity_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 0);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * How many units
 *
 * @returns {number}
 */
gomschema.Trade.prototype.units = function() {
  return this.bb.readUint32(this.bb_pos + 8);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Trade.prototype.mutate_units = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * How many credits
 *
 * @returns {number}
 */
gomschema.Trade.prototype.credits = function() {
  return this.bb.readUint16(this.bb_pos + 12);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Trade.prototype.mutate_credits = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint16(this.bb_pos + offset, value);
  return true;
};

/**
 * Unix timestamp UTC.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.Trade.prototype.timestampUtc = function() {
  return this.bb.readUint64(this.bb_pos + 16);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.Trade.prototype.mutate_timestamp_utc = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} commodity_id
 * @param {number} units
 * @param {number} credits
 * @param {flatbuffers.Long} timestamp_utc
 * @returns {flatbuffers.Offset}
 */
gomschema.Trade.createTrade = function(builder, commodity_id, units, credits, timestamp_utc) {
  builder.prep(8, 24);
  builder.writeInt64(timestamp_utc);
  builder.pad(2);
  builder.writeInt16(credits);
  builder.writeInt32(units);
  builder.writeInt64(commodity_id);
  return builder.offset();
};

/**
 * @constructor
 */
gomschema.FacilityListing = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.FacilityListing}
 */
gomschema.FacilityListing.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {gomschema.FacilityListing=} obj
 * @returns {gomschema.FacilityListing}
 */
gomschema.FacilityListing.getRootAsFacilityListing = function(bb, obj) {
  return (obj || new gomschema.FacilityListing).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * Identifies the facility presenting these trades.
 *
 * @returns {number}
 */
gomschema.FacilityListing.prototype.facilityId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.FacilityListing.prototype.mutate_facility_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * Commodities this facility sells.
 *
 * @param {number} index
 * @param {gomschema.Trade=} obj
 * @returns {gomschema.Trade}
 */
gomschema.FacilityListing.prototype.supply = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new gomschema.Trade).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
gomschema.FacilityListing.prototype.supplyLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * Commodities this facility buys.
 *
 * @param {number} index
 * @param {gomschema.Trade=} obj
 * @returns {gomschema.Trade}
 */
gomschema.FacilityListing.prototype.demand = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new gomschema.Trade).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
gomschema.FacilityListing.prototype.demandLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
gomschema.FacilityListing.startFacilityListing = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} facilityId
 */
gomschema.FacilityListing.addFacilityId = function(builder, facilityId) {
  builder.addFieldInt32(0, facilityId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} supplyOffset
 */
gomschema.FacilityListing.addSupply = function(builder, supplyOffset) {
  builder.addFieldOffset(1, supplyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
gomschema.FacilityListing.startSupplyVector = function(builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} demandOffset
 */
gomschema.FacilityListing.addDemand = function(builder, demandOffset) {
  builder.addFieldOffset(2, demandOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
gomschema.FacilityListing.startDemandVector = function(builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
gomschema.FacilityListing.endFacilityListing = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} facilityId
 * @param {flatbuffers.Offset} supplyOffset
 * @param {flatbuffers.Offset} demandOffset
 * @returns {flatbuffers.Offset}
 */
gomschema.FacilityListing.createFacilityListing = function(builder, facilityId, supplyOffset, demandOffset) {
  gomschema.FacilityListing.startFacilityListing(builder);
  gomschema.FacilityListing.addFacilityId(builder, facilityId);
  gomschema.FacilityListing.addSupply(builder, supplyOffset);
  gomschema.FacilityListing.addDemand(builder, demandOffset);
  return gomschema.FacilityListing.endFacilityListing(builder);
}

/**
 * Facility represents a static, dockable entity within the game such as a station or planetary base.
 * Instead of assigning stations their own unique IDs, we produce an fnv1a_32 hash of the system name
 * and the station name.
 *
 * @constructor
 */
gomschema.Facility = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.Facility}
 */
gomschema.Facility.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {gomschema.Facility=} obj
 * @returns {gomschema.Facility}
 */
gomschema.Facility.getRootAsFacility = function(bb, obj) {
  return (obj || new gomschema.Facility).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * "{upper system name}@{facility name upper}"
 *
 * @returns {number}
 */
gomschema.Facility.prototype.facilityId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_facility_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * Hash of the all-upper name of the system.
 *
 * @returns {number}
 */
gomschema.Facility.prototype.systemId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_system_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * Name of the facility itself.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Facility.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * Unix timestamp UTC of last update.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.Facility.prototype.timestampUtc = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_timestamp_utc = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * Optional facility type.
 *
 * @returns {gomschema.FacilityType}
 */
gomschema.Facility.prototype.facilityType = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? /** @type {gomschema.FacilityType} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.FacilityType.None;
};

/**
 * @param {gomschema.FacilityType} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_facility_type = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 12);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Does it have an accessible trade market.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasMarket = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_market = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Does it have a black market.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasBlackMarket = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_black_market = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Can it refuel.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasRefuel = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_refuel = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 18);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Can it repair.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasRepair = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_repair = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 20);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Can it re-arm.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasRearm = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_rearm = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 22);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Does it sell/upgrade ship components.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasOutfitting = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_outfitting = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 24);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Can you buy ships here.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasShipyard = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_shipyard = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 26);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Can you dock here (this is taken from EDDB and might be redundant).
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasDocking = function() {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_docking = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 28);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Does the market have regular trading commodities available.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.hasCommodities = function() {
  var offset = this.bb.__offset(this.bb_pos, 30);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_has_commodities = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 30);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Is it on a planet.
 *
 * @returns {boolean}
 */
gomschema.Facility.prototype.isPlanetary = function() {
  var offset = this.bb.__offset(this.bb_pos, 32);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_is_planetary = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 32);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Distance from the facility to the entry point in the system.
 *
 * @returns {number}
 */
gomschema.Facility.prototype.lsToStar = function() {
  var offset = this.bb.__offset(this.bb_pos, 34);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_ls_to_star = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 34);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * The governance of this station. If not present, assume system's government.
 *
 * @returns {gomschema.Government}
 */
gomschema.Facility.prototype.government = function() {
  var offset = this.bb.__offset(this.bb_pos, 36);
  return offset ? /** @type {gomschema.Government} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.Government.Corporate;
};

/**
 * @param {gomschema.Government} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_government = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 36);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * The allegiance of this station. If not present, assume system's allegiance.
 *
 * @returns {gomschema.Allegiance}
 */
gomschema.Facility.prototype.allegiance = function() {
  var offset = this.bb.__offset(this.bb_pos, 38);
  return offset ? /** @type {gomschema.Allegiance} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.Allegiance.Independent;
};

/**
 * @param {gomschema.Allegiance} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_allegiance = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 38);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Presumably the internal ED identifier for the market here.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.Facility.prototype.edMarketId = function() {
  var offset = this.bb.__offset(this.bb_pos, 40);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.Facility.prototype.mutate_ed_market_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 40);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 */
gomschema.Facility.startFacility = function(builder) {
  builder.startObject(19);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} facilityId
 */
gomschema.Facility.addFacilityId = function(builder, facilityId) {
  builder.addFieldInt32(0, facilityId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} systemId
 */
gomschema.Facility.addSystemId = function(builder, systemId) {
  builder.addFieldInt32(1, systemId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
gomschema.Facility.addName = function(builder, nameOffset) {
  builder.addFieldOffset(2, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestampUtc
 */
gomschema.Facility.addTimestampUtc = function(builder, timestampUtc) {
  builder.addFieldInt64(3, timestampUtc, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.FacilityType} facilityType
 */
gomschema.Facility.addFacilityType = function(builder, facilityType) {
  builder.addFieldInt8(4, facilityType, gomschema.FacilityType.None);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasMarket
 */
gomschema.Facility.addHasMarket = function(builder, hasMarket) {
  builder.addFieldInt8(5, +hasMarket, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasBlackMarket
 */
gomschema.Facility.addHasBlackMarket = function(builder, hasBlackMarket) {
  builder.addFieldInt8(6, +hasBlackMarket, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasRefuel
 */
gomschema.Facility.addHasRefuel = function(builder, hasRefuel) {
  builder.addFieldInt8(7, +hasRefuel, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasRepair
 */
gomschema.Facility.addHasRepair = function(builder, hasRepair) {
  builder.addFieldInt8(8, +hasRepair, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasRearm
 */
gomschema.Facility.addHasRearm = function(builder, hasRearm) {
  builder.addFieldInt8(9, +hasRearm, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasOutfitting
 */
gomschema.Facility.addHasOutfitting = function(builder, hasOutfitting) {
  builder.addFieldInt8(10, +hasOutfitting, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasShipyard
 */
gomschema.Facility.addHasShipyard = function(builder, hasShipyard) {
  builder.addFieldInt8(11, +hasShipyard, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasDocking
 */
gomschema.Facility.addHasDocking = function(builder, hasDocking) {
  builder.addFieldInt8(12, +hasDocking, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} hasCommodities
 */
gomschema.Facility.addHasCommodities = function(builder, hasCommodities) {
  builder.addFieldInt8(13, +hasCommodities, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isPlanetary
 */
gomschema.Facility.addIsPlanetary = function(builder, isPlanetary) {
  builder.addFieldInt8(14, +isPlanetary, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} lsToStar
 */
gomschema.Facility.addLsToStar = function(builder, lsToStar) {
  builder.addFieldInt32(15, lsToStar, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.Government} government
 */
gomschema.Facility.addGovernment = function(builder, government) {
  builder.addFieldInt8(16, government, gomschema.Government.Corporate);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.Allegiance} allegiance
 */
gomschema.Facility.addAllegiance = function(builder, allegiance) {
  builder.addFieldInt8(17, allegiance, gomschema.Allegiance.Independent);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} edMarketId
 */
gomschema.Facility.addEdMarketId = function(builder, edMarketId) {
  builder.addFieldInt64(18, edMarketId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
gomschema.Facility.endFacility = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} facilityId
 * @param {number} systemId
 * @param {flatbuffers.Offset} nameOffset
 * @param {flatbuffers.Long} timestampUtc
 * @param {gomschema.FacilityType} facilityType
 * @param {boolean} hasMarket
 * @param {boolean} hasBlackMarket
 * @param {boolean} hasRefuel
 * @param {boolean} hasRepair
 * @param {boolean} hasRearm
 * @param {boolean} hasOutfitting
 * @param {boolean} hasShipyard
 * @param {boolean} hasDocking
 * @param {boolean} hasCommodities
 * @param {boolean} isPlanetary
 * @param {number} lsToStar
 * @param {gomschema.Government} government
 * @param {gomschema.Allegiance} allegiance
 * @param {flatbuffers.Long} edMarketId
 * @returns {flatbuffers.Offset}
 */
gomschema.Facility.createFacility = function(builder, facilityId, systemId, nameOffset, timestampUtc, facilityType, hasMarket, hasBlackMarket, hasRefuel, hasRepair, hasRearm, hasOutfitting, hasShipyard, hasDocking, hasCommodities, isPlanetary, lsToStar, government, allegiance, edMarketId) {
  gomschema.Facility.startFacility(builder);
  gomschema.Facility.addFacilityId(builder, facilityId);
  gomschema.Facility.addSystemId(builder, systemId);
  gomschema.Facility.addName(builder, nameOffset);
  gomschema.Facility.addTimestampUtc(builder, timestampUtc);
  gomschema.Facility.addFacilityType(builder, facilityType);
  gomschema.Facility.addHasMarket(builder, hasMarket);
  gomschema.Facility.addHasBlackMarket(builder, hasBlackMarket);
  gomschema.Facility.addHasRefuel(builder, hasRefuel);
  gomschema.Facility.addHasRepair(builder, hasRepair);
  gomschema.Facility.addHasRearm(builder, hasRearm);
  gomschema.Facility.addHasOutfitting(builder, hasOutfitting);
  gomschema.Facility.addHasShipyard(builder, hasShipyard);
  gomschema.Facility.addHasDocking(builder, hasDocking);
  gomschema.Facility.addHasCommodities(builder, hasCommodities);
  gomschema.Facility.addIsPlanetary(builder, isPlanetary);
  gomschema.Facility.addLsToStar(builder, lsToStar);
  gomschema.Facility.addGovernment(builder, government);
  gomschema.Facility.addAllegiance(builder, allegiance);
  gomschema.Facility.addEdMarketId(builder, edMarketId);
  return gomschema.Facility.endFacility(builder);
}

/**
 * Galactic coordinate for a system.
 *
 * @constructor
 */
gomschema.Coordinate = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.Coordinate}
 */
gomschema.Coordinate.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
gomschema.Coordinate.prototype.x = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Coordinate.prototype.mutate_x = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 0);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
gomschema.Coordinate.prototype.y = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Coordinate.prototype.mutate_y = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @returns {number}
 */
gomschema.Coordinate.prototype.z = function() {
  return this.bb.readFloat64(this.bb_pos + 16);
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.Coordinate.prototype.mutate_z = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeFloat64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
gomschema.Coordinate.createCoordinate = function(builder, x, y, z) {
  builder.prep(8, 24);
  builder.writeFloat64(z);
  builder.writeFloat64(y);
  builder.writeFloat64(x);
  return builder.offset();
};

/**
 * System corresponds to an individual Elite-Dangerous star system, akin to a map.
 *
 * @constructor
 */
gomschema.System = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.System}
 */
gomschema.System.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {gomschema.System=} obj
 * @returns {gomschema.System}
 */
gomschema.System.getRootAsSystem = function(bb, obj) {
  return (obj || new gomschema.System).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * System ID is it's upper-cased name hashed via fnv1a.
 *
 * @returns {number}
 */
gomschema.System.prototype.systemId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_system_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint32(this.bb_pos + offset, value);
  return true;
};

/**
 * Unique name of the system.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.System.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * Position in the galaxy.
 *
 * @param {gomschema.Coordinate=} obj
 * @returns {gomschema.Coordinate|null}
 */
gomschema.System.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new gomschema.Coordinate).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * Timestamp of the last update to this entry UTC.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.System.prototype.timestampUtc = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_timestamp_utc = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.System.prototype.power = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * Whether anyone lives here.
 *
 * @returns {boolean}
 */
gomschema.System.prototype.populated = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_populated = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 14);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Whether a permit is required to enter the systme.
 *
 * @returns {boolean}
 */
gomschema.System.prototype.needsPermit = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {boolean} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_needs_permit = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 16);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Law-Enforcement level of the system.
 *
 * @returns {gomschema.SecurityLevel}
 */
gomschema.System.prototype.security = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? /** @type {gomschema.SecurityLevel} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.SecurityLevel.Medium;
};

/**
 * @param {gomschema.SecurityLevel} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_security = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 18);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * What is the government for the system.
 *
 * @returns {gomschema.Government}
 */
gomschema.System.prototype.governmentId = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? /** @type {gomschema.Government} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.Government.Corporate;
};

/**
 * @param {gomschema.Government} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_government_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 20);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Which faction is the system allied to.
 *
 * @returns {gomschema.Allegiance}
 */
gomschema.System.prototype.allegianceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? /** @type {gomschema.Allegiance} */ (this.bb.readInt8(this.bb_pos + offset)) : gomschema.Allegiance.Independent;
};

/**
 * @param {gomschema.Allegiance} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_allegiance_id = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 22);

  if (offset === 0) {
    return false;
  }

  this.bb.writeInt8(this.bb_pos + offset, value);
  return true;
};

/**
 * Guess: Elite Dangerous Internal ID
 *
 * @returns {flatbuffers.Long}
 */
gomschema.System.prototype.edAddress = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.System.prototype.mutate_ed_address = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 24);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * Facilities in this system.
 *
 * @param {number} index
 * @param {gomschema.Facility=} obj
 * @returns {gomschema.Facility}
 */
gomschema.System.prototype.facilities = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? (obj || new gomschema.Facility).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
gomschema.System.prototype.facilitiesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
gomschema.System.startSystem = function(builder) {
  builder.startObject(12);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} systemId
 */
gomschema.System.addSystemId = function(builder, systemId) {
  builder.addFieldInt32(0, systemId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
gomschema.System.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
gomschema.System.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(2, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestampUtc
 */
gomschema.System.addTimestampUtc = function(builder, timestampUtc) {
  builder.addFieldInt64(3, timestampUtc, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} powerOffset
 */
gomschema.System.addPower = function(builder, powerOffset) {
  builder.addFieldOffset(4, powerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} populated
 */
gomschema.System.addPopulated = function(builder, populated) {
  builder.addFieldInt8(5, +populated, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} needsPermit
 */
gomschema.System.addNeedsPermit = function(builder, needsPermit) {
  builder.addFieldInt8(6, +needsPermit, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.SecurityLevel} security
 */
gomschema.System.addSecurity = function(builder, security) {
  builder.addFieldInt8(7, security, gomschema.SecurityLevel.Medium);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.Government} governmentId
 */
gomschema.System.addGovernmentId = function(builder, governmentId) {
  builder.addFieldInt8(8, governmentId, gomschema.Government.Corporate);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {gomschema.Allegiance} allegianceId
 */
gomschema.System.addAllegianceId = function(builder, allegianceId) {
  builder.addFieldInt8(9, allegianceId, gomschema.Allegiance.Independent);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} edAddress
 */
gomschema.System.addEdAddress = function(builder, edAddress) {
  builder.addFieldInt64(10, edAddress, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} facilitiesOffset
 */
gomschema.System.addFacilities = function(builder, facilitiesOffset) {
  builder.addFieldOffset(11, facilitiesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
gomschema.System.createFacilitiesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
gomschema.System.startFacilitiesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
gomschema.System.endSystem = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} systemId
 * @param {flatbuffers.Offset} nameOffset
 * @param {flatbuffers.Offset} positionOffset
 * @param {flatbuffers.Long} timestampUtc
 * @param {flatbuffers.Offset} powerOffset
 * @param {boolean} populated
 * @param {boolean} needsPermit
 * @param {gomschema.SecurityLevel} security
 * @param {gomschema.Government} governmentId
 * @param {gomschema.Allegiance} allegianceId
 * @param {flatbuffers.Long} edAddress
 * @param {flatbuffers.Offset} facilitiesOffset
 * @returns {flatbuffers.Offset}
 */
gomschema.System.createSystem = function(builder, systemId, nameOffset, positionOffset, timestampUtc, powerOffset, populated, needsPermit, security, governmentId, allegianceId, edAddress, facilitiesOffset) {
  gomschema.System.startSystem(builder);
  gomschema.System.addSystemId(builder, systemId);
  gomschema.System.addName(builder, nameOffset);
  gomschema.System.addPosition(builder, positionOffset);
  gomschema.System.addTimestampUtc(builder, timestampUtc);
  gomschema.System.addPower(builder, powerOffset);
  gomschema.System.addPopulated(builder, populated);
  gomschema.System.addNeedsPermit(builder, needsPermit);
  gomschema.System.addSecurity(builder, security);
  gomschema.System.addGovernmentId(builder, governmentId);
  gomschema.System.addAllegianceId(builder, allegianceId);
  gomschema.System.addEdAddress(builder, edAddress);
  gomschema.System.addFacilities(builder, facilitiesOffset);
  return gomschema.System.endSystem(builder);
}

/**
 * Encapsulation of all the data.
 *
 * @constructor
 */
gomschema.Galaxy = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {gomschema.Galaxy}
 */
gomschema.Galaxy.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {gomschema.Galaxy=} obj
 * @returns {gomschema.Galaxy}
 */
gomschema.Galaxy.getRootAsGalaxy = function(bb, obj) {
  return (obj || new gomschema.Galaxy).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
gomschema.Galaxy.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('gomd');
};

/**
 * Semantically-versioned schema id.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.schemaVersion = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * Human-friendly description of what is enclosed, e.g "import from source X" or
 * "complete local database". Entirely descriptive.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.description = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * Human-friendly attributition, if relevant.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.attribution = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * UTC Unix time of generation.
 *
 * @returns {flatbuffers.Long}
 */
gomschema.Galaxy.prototype.timestampUtc = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Long} value
 * @returns {boolean}
 */
gomschema.Galaxy.prototype.mutate_timestamp_utc = function(value) {
  var offset = this.bb.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb.writeUint64(this.bb_pos + offset, value);
  return true;
};

/**
 * Items recognized by this data.
 *
 * @param {number} index
 * @param {gomschema.Commodity=} obj
 * @returns {gomschema.Commodity}
 */
gomschema.Galaxy.prototype.commodities = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new gomschema.Commodity).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
gomschema.Galaxy.prototype.commoditiesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * Systems recognized by this data (presence of facilities optional).
 *
 * @param {number} index
 * @param {gomschema.System=} obj
 * @returns {gomschema.System}
 */
gomschema.Galaxy.prototype.systems = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new gomschema.System).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
gomschema.Galaxy.prototype.systemsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * Fields reserved for any user-specific notes.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.userData = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * 3rd-party application values that prefer .ini format.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.iniData = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * 3rd-party application values that prefer .json format.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.jsonData = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * 3rd-party application values that prefer .yaml because they hate life.
 *
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
gomschema.Galaxy.prototype.yamlData = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
gomschema.Galaxy.startGalaxy = function(builder) {
  builder.startObject(10);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} schemaVersionOffset
 */
gomschema.Galaxy.addSchemaVersion = function(builder, schemaVersionOffset) {
  builder.addFieldOffset(0, schemaVersionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} descriptionOffset
 */
gomschema.Galaxy.addDescription = function(builder, descriptionOffset) {
  builder.addFieldOffset(1, descriptionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributionOffset
 */
gomschema.Galaxy.addAttribution = function(builder, attributionOffset) {
  builder.addFieldOffset(2, attributionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestampUtc
 */
gomschema.Galaxy.addTimestampUtc = function(builder, timestampUtc) {
  builder.addFieldInt64(3, timestampUtc, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} commoditiesOffset
 */
gomschema.Galaxy.addCommodities = function(builder, commoditiesOffset) {
  builder.addFieldOffset(4, commoditiesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
gomschema.Galaxy.createCommoditiesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
gomschema.Galaxy.startCommoditiesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} systemsOffset
 */
gomschema.Galaxy.addSystems = function(builder, systemsOffset) {
  builder.addFieldOffset(5, systemsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
gomschema.Galaxy.createSystemsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
gomschema.Galaxy.startSystemsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} userDataOffset
 */
gomschema.Galaxy.addUserData = function(builder, userDataOffset) {
  builder.addFieldOffset(6, userDataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} iniDataOffset
 */
gomschema.Galaxy.addIniData = function(builder, iniDataOffset) {
  builder.addFieldOffset(7, iniDataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} jsonDataOffset
 */
gomschema.Galaxy.addJsonData = function(builder, jsonDataOffset) {
  builder.addFieldOffset(8, jsonDataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} yamlDataOffset
 */
gomschema.Galaxy.addYamlData = function(builder, yamlDataOffset) {
  builder.addFieldOffset(9, yamlDataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
gomschema.Galaxy.endGalaxy = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
gomschema.Galaxy.finishGalaxyBuffer = function(builder, offset) {
  builder.finish(offset, 'gomd');
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} schemaVersionOffset
 * @param {flatbuffers.Offset} descriptionOffset
 * @param {flatbuffers.Offset} attributionOffset
 * @param {flatbuffers.Long} timestampUtc
 * @param {flatbuffers.Offset} commoditiesOffset
 * @param {flatbuffers.Offset} systemsOffset
 * @param {flatbuffers.Offset} userDataOffset
 * @param {flatbuffers.Offset} iniDataOffset
 * @param {flatbuffers.Offset} jsonDataOffset
 * @param {flatbuffers.Offset} yamlDataOffset
 * @returns {flatbuffers.Offset}
 */
gomschema.Galaxy.createGalaxy = function(builder, schemaVersionOffset, descriptionOffset, attributionOffset, timestampUtc, commoditiesOffset, systemsOffset, userDataOffset, iniDataOffset, jsonDataOffset, yamlDataOffset) {
  gomschema.Galaxy.startGalaxy(builder);
  gomschema.Galaxy.addSchemaVersion(builder, schemaVersionOffset);
  gomschema.Galaxy.addDescription(builder, descriptionOffset);
  gomschema.Galaxy.addAttribution(builder, attributionOffset);
  gomschema.Galaxy.addTimestampUtc(builder, timestampUtc);
  gomschema.Galaxy.addCommodities(builder, commoditiesOffset);
  gomschema.Galaxy.addSystems(builder, systemsOffset);
  gomschema.Galaxy.addUserData(builder, userDataOffset);
  gomschema.Galaxy.addIniData(builder, iniDataOffset);
  gomschema.Galaxy.addJsonData(builder, jsonDataOffset);
  gomschema.Galaxy.addYamlData(builder, yamlDataOffset);
  return gomschema.Galaxy.endGalaxy(builder);
}

// Exports for Node.js and RequireJS
this.gomschema = gomschema;
