# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gomschema

# /// Security level is system-specific and determines how aggressive law enforcement is.
class SecurityLevel(object):
    None_ = 0
    Anarchy = 1
    Low = 2
    Medium = 3
    High = 4

