// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ettuschema
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Galactic coordinate for a system.
public struct Coordinate : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Coordinate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double X { get { return __p.bb.GetDouble(__p.bb_pos + 0); } }
  public void MutateX(double x) { __p.bb.PutDouble(__p.bb_pos + 0, x); }
  public double Y { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }
  public void MutateY(double y) { __p.bb.PutDouble(__p.bb_pos + 8, y); }
  public double Z { get { return __p.bb.GetDouble(__p.bb_pos + 16); } }
  public void MutateZ(double z) { __p.bb.PutDouble(__p.bb_pos + 16, z); }

  public static Offset<ettuschema.Coordinate> CreateCoordinate(FlatBufferBuilder builder, double X, double Y, double Z) {
    builder.Prep(8, 24);
    builder.PutDouble(Z);
    builder.PutDouble(Y);
    builder.PutDouble(X);
    return new Offset<ettuschema.Coordinate>(builder.Offset);
  }
};


}
