// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ettuschema
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Encapsulation of all the data.
public struct Galaxy : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Galaxy GetRootAsGalaxy(ByteBuffer _bb) { return GetRootAsGalaxy(_bb, new Galaxy()); }
  public static Galaxy GetRootAsGalaxy(ByteBuffer _bb, Galaxy obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool GalaxyBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "gomd"); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Galaxy __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Semantically-versioned schema id.
  public string SchemaVersion { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSchemaVersionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSchemaVersionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSchemaVersionArray() { return __p.__vector_as_array<byte>(4); }
  /// Human-friendly description of what is enclosed, e.g "import from source X" or
  /// "complete local database". Entirely descriptive.
  public string Description { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(6); }
  /// Human-friendly attributition, if relevant.
  public string Attribution { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAttributionBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetAttributionBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetAttributionArray() { return __p.__vector_as_array<byte>(8); }
  /// UTC Unix time of generation.
  public ulong TimestampUtc { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public bool MutateTimestampUtc(ulong timestamp_utc) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutUlong(o + __p.bb_pos, timestamp_utc); return true; } else { return false; } }
  /// Items recognized by this data.
  public ettuschema.Commodity? Commodities(int j) { int o = __p.__offset(12); return o != 0 ? (ettuschema.Commodity?)(new ettuschema.Commodity()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CommoditiesLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ettuschema.Commodity? CommoditiesByKey(ulong key) { int o = __p.__offset(12); return o != 0 ? ettuschema.Commodity.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  /// Systems recognized by this data (presence of facilities optional).
  public ettuschema.System? Systems(int j) { int o = __p.__offset(14); return o != 0 ? (ettuschema.System?)(new ettuschema.System()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SystemsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ettuschema.System? SystemsByKey(uint key) { int o = __p.__offset(14); return o != 0 ? ettuschema.System.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  /// Fields reserved for any user-specific notes.
  public string UserData { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserDataBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetUserDataBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetUserDataArray() { return __p.__vector_as_array<byte>(16); }
  /// 3rd-party application values that prefer .ini format.
  public string IniData { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIniDataBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetIniDataBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetIniDataArray() { return __p.__vector_as_array<byte>(18); }
  /// 3rd-party application values that prefer .json format.
  public string JsonData { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetJsonDataBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetJsonDataBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetJsonDataArray() { return __p.__vector_as_array<byte>(20); }
  /// 3rd-party application values that prefer .yaml because they hate life.
  public string YamlData { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetYamlDataBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetYamlDataBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetYamlDataArray() { return __p.__vector_as_array<byte>(22); }

  public static Offset<ettuschema.Galaxy> CreateGalaxy(FlatBufferBuilder builder,
      StringOffset schema_versionOffset = default(StringOffset),
      StringOffset descriptionOffset = default(StringOffset),
      StringOffset attributionOffset = default(StringOffset),
      ulong timestamp_utc = 0,
      VectorOffset commoditiesOffset = default(VectorOffset),
      VectorOffset systemsOffset = default(VectorOffset),
      StringOffset user_dataOffset = default(StringOffset),
      StringOffset ini_dataOffset = default(StringOffset),
      StringOffset json_dataOffset = default(StringOffset),
      StringOffset yaml_dataOffset = default(StringOffset)) {
    builder.StartTable(10);
    Galaxy.AddTimestampUtc(builder, timestamp_utc);
    Galaxy.AddYamlData(builder, yaml_dataOffset);
    Galaxy.AddJsonData(builder, json_dataOffset);
    Galaxy.AddIniData(builder, ini_dataOffset);
    Galaxy.AddUserData(builder, user_dataOffset);
    Galaxy.AddSystems(builder, systemsOffset);
    Galaxy.AddCommodities(builder, commoditiesOffset);
    Galaxy.AddAttribution(builder, attributionOffset);
    Galaxy.AddDescription(builder, descriptionOffset);
    Galaxy.AddSchemaVersion(builder, schema_versionOffset);
    return Galaxy.EndGalaxy(builder);
  }

  public static void StartGalaxy(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddSchemaVersion(FlatBufferBuilder builder, StringOffset schemaVersionOffset) { builder.AddOffset(0, schemaVersionOffset.Value, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset descriptionOffset) { builder.AddOffset(1, descriptionOffset.Value, 0); }
  public static void AddAttribution(FlatBufferBuilder builder, StringOffset attributionOffset) { builder.AddOffset(2, attributionOffset.Value, 0); }
  public static void AddTimestampUtc(FlatBufferBuilder builder, ulong timestampUtc) { builder.AddUlong(3, timestampUtc, 0); }
  public static void AddCommodities(FlatBufferBuilder builder, VectorOffset commoditiesOffset) { builder.AddOffset(4, commoditiesOffset.Value, 0); }
  public static VectorOffset CreateCommoditiesVector(FlatBufferBuilder builder, Offset<ettuschema.Commodity>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCommoditiesVectorBlock(FlatBufferBuilder builder, Offset<ettuschema.Commodity>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartCommoditiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSystems(FlatBufferBuilder builder, VectorOffset systemsOffset) { builder.AddOffset(5, systemsOffset.Value, 0); }
  public static VectorOffset CreateSystemsVector(FlatBufferBuilder builder, Offset<ettuschema.System>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSystemsVectorBlock(FlatBufferBuilder builder, Offset<ettuschema.System>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSystemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUserData(FlatBufferBuilder builder, StringOffset userDataOffset) { builder.AddOffset(6, userDataOffset.Value, 0); }
  public static void AddIniData(FlatBufferBuilder builder, StringOffset iniDataOffset) { builder.AddOffset(7, iniDataOffset.Value, 0); }
  public static void AddJsonData(FlatBufferBuilder builder, StringOffset jsonDataOffset) { builder.AddOffset(8, jsonDataOffset.Value, 0); }
  public static void AddYamlData(FlatBufferBuilder builder, StringOffset yamlDataOffset) { builder.AddOffset(9, yamlDataOffset.Value, 0); }
  public static Offset<ettuschema.Galaxy> EndGalaxy(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ettuschema.Galaxy>(o);
  }
  public static void FinishGalaxyBuffer(FlatBufferBuilder builder, Offset<ettuschema.Galaxy> offset) { builder.Finish(offset.Value, "gomd"); }
  public static void FinishSizePrefixedGalaxyBuffer(FlatBufferBuilder builder, Offset<ettuschema.Galaxy> offset) { builder.FinishSizePrefixed(offset.Value, "gomd"); }
};


}
