on: push

jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - uses: actions/setup-go@master
              with:
                  go-version: "1.14"
            - name: "Run tests"
              run: go test -v -coverprofile="coverage.prof" .
            - name: "Emit coverage"
              run: go tool cover -func="coverage.prof"
